name: Build and Release Vault CLI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/vault cmd/vault/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/vault.exe cmd/vault/main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/vault-mac cmd/vault/main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vault-binaries
          path: bin/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build release binaries
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/vault cmd/vault/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/vault.exe cmd/vault/main.go
          GOOS=darwin GOARCH=amd64 go build -o bin/vault-mac cmd/vault/main.go

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
