name: Release

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/vault-linux-amd64 ./cmd/vault
          GOOS=linux   GOARCH=arm64 go build -o dist/vault-linux-arm64 ./cmd/vault
          GOOS=darwin  GOARCH=amd64 go build -o dist/vault-darwin-amd64 ./cmd/vault
          GOOS=darwin  GOARCH=arm64 go build -o dist/vault-darwin-arm64 ./cmd/vault
          GOOS=windows GOARCH=amd64 go build -o dist/vault-windows-amd64.exe ./cmd/vault

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
